### ISSUE TITLE
Keep getting /.bin/eww is not a directory when executing launch script 

### ISSUE THREAD

**Issue by KevinApodaca** [adi1090x/widgets#1]
Did this step 
> Copy eww executable to $HOME/.bin (create directory if not exist)`

using the command `cp ./eww $HOME/.bin` from the official /eww/target/release directory.

installed both fonts in fonts directory and copied files from `nordic` to root eww config folder. 

Launched dameon and then `launch_eww` script. 

Screenshot of outputs included. Any idea what I messed up on ? thanks!
![Screenshot_2021-06-20-08-04-10_1244x1358](https://user-images.githubusercontent.com/35210520/122694406-d6c60000-d202-11eb-98bd-290494c42bcc.png)

**Comment by shivanshu-semwal** [comment]
edit the `launch_eww` script, do these modifications

```bash
## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/eww/target/release/eww"
```

**Comment by KevinApodaca** [comment]
> edit the `launch_eww` script, do these modifications
> 
> ```shell
> ## Files and cmd
> FILE="$HOME/.cache/eww_launch.xyz"
> EWW="$HOME/eww/target/release/eww"
> ```

Yup that solved it, thanks!

**Comment by d2rgaming-9000** [comment]
I'll check this fix.

**Comment by d2rgaming-9000** [comment]
Nope.
