### ISSUE TITLE
Setup EWW

### ISSUE THREAD

**Issue by igmt-official** [adi1090x/widgets#10]
hello, i love your work, but sadly i don't know how can i setup the widgets on my Qtile, your instruction for installing EWW is outdated the website is server error.

**Comment by mmsaeed509** [comment]
[Eww Documentation](https://elkowar.github.io/eww/) read this doc to install eww
or run these commands

```bash

sudo pacman -S rustup

git clone https://github.com/elkowar/eww

cd eww

```
Before building, you must know the display server used on your machine (Xorg or Wayland) 

run this command to know `echo $XDG_SESSION_TYPE`

if the output = `wayland`

build eww `cargo build --release --no-default-features --features=wayland`

output `x11` or else `cargo build --release`

then

```bash
cd target/release
chmod +x ./eww
sudo cp eww /bin
```
then clone widgets

```bash

git clone  https://github.com/adi1090x/widgets.git

cd widgets

mkdir -p ~/.config/eww

cp -r dashboard ~/.config/eww

```
hint :
copy launch_dashboard to the /bin or /usr/bin to access it from anywhere 

 `cp ~/.config/eww/dashboard/launch_dashboard /bin/`

I hope this can help you @igmt-official

**Comment by igmt-official** [comment]
thank you 🥰

**Comment by mmsaeed509** [comment]
I forgot to tell you about the setup Keybinding  :sweat_smile:
to run the widget `bash ~/.config/eww/dashboard/launch_dashboard` in terminal
or copy launch_dashboard to the /bin `cp ~/.config/eww/dashboard/launch_dashboard /bin/`
run  `launch_dashboard` in terminal

or setup Keybinding in ***bspwm***
edit `~/.config/sxhkd/sxhkdrc` and add these lines
```
# Open/close dashboard
super + d
	launch_dashboard
```
super+d open/close the widget
