### ISSUE TITLE
About Icons in Arin Widget

### ISSUE THREAD

**Issue by satyatejatanuku** [adi1090x/widgets#12]
I wanna replace some icons in top bar with other (like whatsapp, vs code). Can share some details about the icons you used over there?

**Comment by Quadrubo** [comment]
Second this, would be nice to know the icon pack so I can match the style

**Comment by amplexus** [comment]
Third this, just want to find icons with a similar look for other apps I use.  Brilliant theme thanks for all your hard work.

**Comment by kiliangui** [comment]
hey ! i'm another one searching for where your icons come from :) I really love the arin bar and i dont want to break it with my ugly icons :3

**Comment by andreyyao** [comment]
After a little bit of hunting it seems that the icons are from the "Crayon" icon pack! Sadly it seems to be not free and not available on Linux

**Comment by adi1090x** [comment]
Yes, I used that one, Crayon it is.
