### ISSUE TITLE
Widgets always on top

### ISSUE THREAD

**Issue by gordnhoo** [adi1090x/widgets#13]
Hello I'm having an issue where the widgets always stay on top of every application what could be causing this ?

**Comment by gordnhoo** [comment]
fixed the issue by applying :windowtype "desktop" but now got another issue now i get his black spots all around and when i click on the desktop both of the widgets disappear
![Screenshot_13](https://user-images.githubusercontent.com/86193036/181815614-7f300041-2e81-471c-a11a-4d27efc1a282.png)

**Comment by stevensonmt** [comment]
You might look at https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm46409506300752 for hints on what to set as the window type.

**Comment by gordnhoo** [comment]
i already tried all of the ones in the documenttion  like :windowtype "desktop" or :windowtype "dock " but non of them work btw im using KDE and debian 
The only one that kinda works is the desktop one but when i click on the desktop all the icons just disappear and i have to eww reload

**Comment by stevensonmt** [comment]
You have to match the window type to the behavior you want. If you make it `dock` the window manager will keep it on top of all other windows, like a taskbar or panel. Desktop is almost certainly not what you want. You probably want normal or just don't set it at all. I'm curious though, where are you setting the windowtype?

**Comment by gordnhoo** [comment]
Yes I understand that but as I said when I leave it blank or try any of the available settings the apps always stay on top except for the desktop option which doesn't stay on top but disappears when the desktop interface is clicked.
If I run the dashboard the whole dashboard takes my screen and stays on top of everything so if i click lets stay the youtube button the YouTube window opens but in the back and i cant leave the dashboard unless i stop eww or run the script that came with the file.

**Comment by stevensonmt** [comment]
what window manager are you using?

**Comment by gordnhoo** [comment]
Im running debian 11 with kde and the default window manager = KWin

**Comment by adi1090x** [comment]
Dashboard widget is meant to be and supposed to **Always on Top**
