### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by LinuxWOW** [adi1090x/widgets#9]
i posted message on reddit. what wm is this. how to install

**Comment by mmsaeed509** [comment]
[Read this](https://github.com/adi1090x/widgets/issues/10#issuecomment-1075551291) for installation

read this for WM : [WM (window manager)](https://wiki.archlinux.org/title/window_manager) it's a simple GUI in Linux desktop

**Comment by adi1090x** [comment]
Eww is WM independent.
